name: yousif_mansi
description: laptops store

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  aligned_dialog: ^0.0.6
  aligned_tooltip: ^0.0.1
  auto_size_text: ^3.0.0
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_storage: ^11.0.0
  flutter_animate: ^3.1.0
  flutter_blurhash: ^0.7.0
  flutter_cache_manager: ^3.3.0
  flutter_rating_bar: ^4.0.0
  google_fonts: ^4.0.0
  provider: ^6.0.0
  rxdart: ^0.27.0
  url_launcher: ^6.0.0
  video_player: ^2.5.0
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: ^0.13.5
  uuid: ^4.0.0
  win32: ^2.6.1

dev_dependencies:
  flutter_lints: ^1.0.0
  image: ^3.2.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: FfUntitledui
      fonts:
        - asset: assets/fonts/ff-untitledui.ttf
