name: yousif_mansi
description: laptops store

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  aligned_dialog: ^0.0.6
  aligned_tooltip: ^0.0.1
  auto_size_text: ^3.0.0
  badges: ^2.0.2
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.2
  flutter_animate: ^4.5.0
  flutter_blurhash: ^0.8.2
  flutter_cache_manager: ^3.4.1
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  provider: ^6.1.2
  rxdart: ^0.27.7
  url_launcher: ^6.3.0
  video_player: ^2.9.2
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: ^1.2.2
  uuid: ^4.0.0
  win32: ^5.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  image: ^4.2.0
  lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: FfUntitledui
      fonts:
        - asset: assets/fonts/ff-untitledui.ttf
